{{- if and .Values.agent.enabled (eq .Values.k8sMode "ROSA" )}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cloudwatch-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    k8Mode: "rosa"
{{- end }}
