{{ if and .Values.agent.enabled (eq .Values.k8sMode "ROSA") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "amazon-cloudwatch-observability.labels" . | nindent 4}}
  name: {{ template "cloudwatch-agent.name" . }}-rosa-role
rules:
- apiGroups: [""]
  resources:
    - nodes
    - nodes/proxy
    - nodes/metrics
    - nodes/stats
  verbs: ["get", "list", "watch"]
- apiGroups: ["", "config.openshift.io"]
  resources: ["pods", "namespaces", "infrastructures", "infrastructures/status"]
  verbs: ["get", "watch", "list"]
- nonResourceURLs: [ "/pods" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [""]
  resources: ["nodes/proxy"]
  verbs: ["get", "list", "watch"]
{{- end }}
