region: us-west-2
clusterName: minikube

agents:
  - name: ci-agent
  - name: appsignals-agent
    mode: deployment
    replicas: 1
    serviceAccount:
      name: appsignals-agent
  - name: cloudwatch-agent-cluster-scraper
    mode: deployment
    replicas: 1
    serviceAccount:
      name: cloudwatch-agent-cluster-scraper

containerInsights:
  enabled: true
  targetAgent: "ci-agent"

applicationSignals:
  enabled: true
  targetAgent: "appsignals-agent"

otelContainerInsights:
  enabled: true
  targetAgent: "ci-agent"
  clusterScraperAgent: "cloudwatch-agent-cluster-scraper"
