// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

package scenarios

import (
	"context"
	"encoding/json"
	"testing"

	"github.com/aws-observability/helm-charts/integration-tests/amazon-cloudwatch-observability/util"
	"github.com/aws-observability/helm-charts/integration-tests/amazon-cloudwatch-observability/validations/minikube"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// TestAgentConfigMergeIsolation verifies that when a customer overrides $.agent.config,
// the cluster-scraper still gets its auto-generated config (not the customer's override).
// This guards against Helm values coalescing leaking $.agent.config into all $.agents entries.
//
// Test scenario values (agent-config-merge-isolation/values.yaml):
//
//	region: us-west-2
//	agent.config is set to an ECI-only config (no AppSignals, no traces).
//	This simulates a customer who overrides $.agent.config to customize the DaemonSet agent.
func TestAgentConfigMergeIsolation(t *testing.T) {
	// Must match the region in agent-config-merge-isolation/values.yaml
	const expectedRegion = "us-west-2"
	// Must match the clusterName in agent-config-merge-isolation/values.yaml
	const expectedClusterName = "minikube"

	k8sClient, err := util.NewK8sClient()
	require.NoError(t, err)

	agentMap := mergeIsolationListAgentCRs(t, k8sClient)

	t.Run("BothAgentCRsExist", func(t *testing.T) {
		_, daemonsetExists := agentMap["cloudwatch-agent"]
		assert.True(t, daemonsetExists, "cloudwatch-agent CR should exist")

		_, scraperExists := agentMap["cloudwatch-agent-cluster-scraper"]
		assert.True(t, scraperExists, "cloudwatch-agent-cluster-scraper CR should exist")
	})

	t.Run("DaemonSetAgentUsesCustomerConfig", func(t *testing.T) {
		config := mergeIsolationGetAgentConfig(t, agentMap, "cloudwatch-agent")

		assert.Contains(t, config, "enhanced_container_insights",
			"cloudwatch-agent should use customer's config containing enhanced_container_insights")

		assert.NotContains(t, config, "application_signals",
			"cloudwatch-agent should use customer's config which does not contain application_signals")

		assert.NotContains(t, config, "traces_collected",
			"cloudwatch-agent should use customer's config which does not contain traces")
	})

	t.Run("ClusterScraperIgnoresCustomerConfig", func(t *testing.T) {
		config := mergeIsolationGetAgentConfig(t, agentMap, "cloudwatch-agent-cluster-scraper")

		assert.NotContains(t, config, "enhanced_container_insights",
			"cluster-scraper should NOT inherit customer's enhanced_container_insights config")

		assert.NotContains(t, config, "application_signals",
			"cluster-scraper should NOT have application_signals")

		assert.NotContains(t, config, "traces_collected",
			"cluster-scraper should NOT have traces")
	})

	t.Run("ClusterScraperConfigMatchesExpectedAutoGenerated", func(t *testing.T) {
		// The definitive test: the cluster-scraper config must exactly match
		// what build-default-config produces for it. This catches the leak
		// regardless of what the customer sets in $.agent.config — even if
		// the customer's config happens to look similar to the auto-generated one.
		//
		// The scenario enables otelContainerInsights, so build-default-config for the
		// cluster-scraper produces two top-level keys:
		//   {"agent":{"region":"<region>"},
		//    "opentelemetry":{"cluster_name":"<clusterName>",
		//                     "collect":{"container_insights":{
		//                        "role":"cluster","collection_interval":30,"solutions":{...}}}}}
		// The container_insights block carries role=cluster + a solutions object and NO logs key
		// (logs are node-only). No AppSignals/ContainerInsights feature flags target the scraper,
		// so there is no top-level "logs" key either.
		config := mergeIsolationGetAgentConfig(t, agentMap, "cloudwatch-agent-cluster-scraper")

		var parsed map[string]interface{}
		err := json.Unmarshal([]byte(config), &parsed)
		require.NoError(t, err, "cluster-scraper config should be valid JSON")

		// Must have exactly two top-level keys: "agent" and "opentelemetry".
		require.Len(t, parsed, 2,
			"cluster-scraper config should have exactly two top-level keys (agent, opentelemetry)")

		agentSection, ok := parsed["agent"].(map[string]interface{})
		require.True(t, ok, "cluster-scraper config should have agent section")
		assert.Equal(t, expectedRegion, agentSection["region"],
			"cluster-scraper config region should match the chart's region value")

		// opentelemetry.cluster_name is a sibling of collect.
		otel, ok := parsed["opentelemetry"].(map[string]interface{})
		require.True(t, ok, "cluster-scraper config should have opentelemetry section")
		assert.Equal(t, expectedClusterName, otel["cluster_name"],
			"cluster-scraper opentelemetry.cluster_name should match the scenario clusterName")

		collect, ok := otel["collect"].(map[string]interface{})
		require.True(t, ok, "cluster-scraper opentelemetry should have a collect block")
		ci, ok := collect["container_insights"].(map[string]interface{})
		require.True(t, ok, "cluster-scraper opentelemetry.collect should have container_insights")

		assert.Equal(t, "cluster", ci["role"],
			"cluster-scraper container_insights.role should be cluster")
		// JSON numbers unmarshal to float64; collection_interval is 30 for this scenario.
		assert.Equal(t, float64(30), ci["collection_interval"],
			"cluster-scraper container_insights.collection_interval should be 30")

		// Cluster role carries NO logs key (logs are node-only after the OTel CI migration).
		_, hasLogs := ci["logs"]
		assert.False(t, hasLogs,
			"cluster-scraper container_insights should NOT include a logs key (logs are node-only)")

		// solutions object: enabled + karpenter{enabled,namespace} + keda{enabled,namespace}.
		solutions, ok := ci["solutions"].(map[string]interface{})
		require.True(t, ok, "cluster-scraper container_insights should include a solutions object")
		assert.Equal(t, true, solutions["enabled"], "solutions.enabled should be true")

		karpenter, ok := solutions["karpenter"].(map[string]interface{})
		require.True(t, ok, "solutions should include karpenter")
		assert.Equal(t, true, karpenter["enabled"], "solutions.karpenter.enabled should be true")
		assert.Equal(t, "kube-system", karpenter["namespace"],
			"solutions.karpenter.namespace should be kube-system")

		keda, ok := solutions["keda"].(map[string]interface{})
		require.True(t, ok, "solutions should include keda")
		assert.Equal(t, true, keda["enabled"], "solutions.keda.enabled should be true")
		assert.Equal(t, "keda", keda["namespace"], "solutions.keda.namespace should be keda")
	})

	t.Run("ClusterScraperIsDeploymentMode", func(t *testing.T) {
		agent, exists := agentMap["cloudwatch-agent-cluster-scraper"]
		require.True(t, exists)

		spec, ok := agent.Object["spec"].(map[string]interface{})
		require.True(t, ok)

		mode, _ := spec["mode"].(string)
		assert.Equal(t, "deployment", mode, "cluster-scraper should be in deployment mode")
	})

	t.Log("Agent config merge isolation validation passed")
}

// mergeIsolationListAgentCRs returns a map of CR name -> CR for all AmazonCloudWatchAgent resources.
func mergeIsolationListAgentCRs(t *testing.T, k8sClient *util.K8sClient) map[string]unstructured.Unstructured {
	t.Helper()

	dynamicClient, err := k8sClient.GetDynamicClient()
	require.NoError(t, err)

	gvr := schema.GroupVersionResource{
		Group:    "cloudwatch.aws.amazon.com",
		Version:  "v1alpha1",
		Resource: "amazoncloudwatchagents",
	}

	agentList, err := dynamicClient.Resource(gvr).Namespace(minikube.Namespace).List(
		context.Background(), metav1.ListOptions{},
	)
	require.NoError(t, err, "failed to list AmazonCloudWatchAgent CRs")

	agentMap := make(map[string]unstructured.Unstructured)
	for _, agent := range agentList.Items {
		agentMap[agent.GetName()] = agent
	}
	return agentMap
}

// mergeIsolationGetAgentConfig extracts the config string from an AmazonCloudWatchAgent CR.
func mergeIsolationGetAgentConfig(t *testing.T, agentMap map[string]unstructured.Unstructured, name string) string {
	t.Helper()

	agent, exists := agentMap[name]
	require.True(t, exists, "%s CR should exist", name)

	spec, ok := agent.Object["spec"].(map[string]interface{})
	require.True(t, ok, "%s should have spec", name)

	config, ok := spec["config"].(string)
	require.True(t, ok, "%s config should be a string", name)

	return config
}
