// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

package scenarios

import (
	"context"
	"testing"

	"github.com/aws-observability/helm-charts/integration-tests/amazon-cloudwatch-observability/util"
	"github.com/aws-observability/helm-charts/integration-tests/amazon-cloudwatch-observability/validations/minikube"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// TestFeatureTargetedCustomOtelConfig verifies that a per-agent otelConfig coexists with OTEL
// Container Insights: CI is generated by the agent from spec.config (JSON, role node) and the
// user's otelConfig is passed through to spec.otelConfig unchanged. The chart no longer merges
// CI into otelConfig or overrides colliding keys — conflicts are rejected by the agent at runtime.
func TestFeatureTargetedCustomOtelConfig(t *testing.T) {
	k8sClient, err := util.NewK8sClient()
	require.NoError(t, err, "failed to create k8s client")

	ns, err := k8sClient.GetNamespace(minikube.Namespace)
	assert.NoError(t, err)
	assert.Equal(t, minikube.Namespace, ns.Name)

	dynamicClient, err := k8sClient.GetDynamicClient()
	require.NoError(t, err, "failed to get dynamic client")

	gvr := schema.GroupVersionResource{
		Group:    "cloudwatch.aws.amazon.com",
		Version:  "v1alpha1",
		Resource: "amazoncloudwatchagents",
	}

	agentList, err := dynamicClient.Resource(gvr).Namespace(minikube.Namespace).List(
		context.Background(), metav1.ListOptions{},
	)
	require.NoError(t, err, "failed to list AmazonCloudWatchAgent CRs")

	agentMap := make(map[string]unstructured.Unstructured)
	for _, agent := range agentList.Items {
		agentMap[agent.GetName()] = agent
	}

	t.Run("ContainerInsightsInSpecConfig", func(t *testing.T) {
		validateContainerInsightsInSpecConfig(t, agentMap)
	})

	t.Run("UserOtelConfigPassedThrough", func(t *testing.T) {
		validateUserOtelConfigPassedThrough(t, agentMap)
	})

	t.Run("UserCustomComponentsPreserved", func(t *testing.T) {
		validateUserCustomComponentsPreserved(t, agentMap)
	})

	t.Log("Feature targeted custom otel config scenario validation passed")
}

// validateContainerInsightsInSpecConfig verifies CI is generated into spec.config (JSON) with
// role node — the agent builds the pipelines from JSON, not the chart from otelConfig.
func validateContainerInsightsInSpecConfig(t *testing.T, agentMap map[string]unstructured.Unstructured) {
	agent, exists := agentMap["cloudwatch-agent"]
	if !assert.True(t, exists, "cloudwatch-agent CR should exist") {
		return
	}
	spec, ok := agent.Object["spec"].(map[string]interface{})
	if !assert.True(t, ok, "spec should be a map") {
		return
	}
	config, ok := spec["config"].(string)
	if !assert.True(t, ok, "spec.config should be a string") {
		return
	}
	minikube.AssertOtelContainerInsights(t, config, "node")
}

// validateUserOtelConfigPassedThrough verifies the user's otelConfig reaches spec.otelConfig
// unchanged. A user value colliding with a CI internal name is preserved here (not overwritten
// by the chart); the agent rejects such conflicts at runtime instead.
func validateUserOtelConfigPassedThrough(t *testing.T, agentMap map[string]unstructured.Unstructured) {
	agent, exists := agentMap["cloudwatch-agent"]
	if !assert.True(t, exists, "cloudwatch-agent CR should exist") {
		return
	}
	spec, ok := agent.Object["spec"].(map[string]interface{})
	if !assert.True(t, ok, "spec should be a map") {
		return
	}
	otelConfig, ok := spec["otelConfig"].(string)
	if !assert.True(t, ok, "otelConfig should be a string") {
		return
	}
	assert.NotEmpty(t, otelConfig, "otelConfig should not be empty")

	// User's colliding value is preserved (chart no longer overrides).
	assert.Contains(t, otelConfig, "us-fake-99",
		"user otelConfig should pass through unchanged (no chart-side override)")
}

// validateUserCustomComponentsPreserved verifies user-supplied components are preserved in otelConfig.
func validateUserCustomComponentsPreserved(t *testing.T, agentMap map[string]unstructured.Unstructured) {
	agent, exists := agentMap["cloudwatch-agent"]
	if !assert.True(t, exists, "cloudwatch-agent CR should exist") {
		return
	}
	spec, ok := agent.Object["spec"].(map[string]interface{})
	if !assert.True(t, ok, "spec should be a map") {
		return
	}
	otelConfig, ok := spec["otelConfig"].(string)
	if !assert.True(t, ok, "otelConfig should be a string") {
		return
	}

	assert.Contains(t, otelConfig, "custom_user_scraper", "user's custom receiver should be preserved")
	assert.Contains(t, otelConfig, "custom_user", "user's custom processor should be preserved")
	assert.Contains(t, otelConfig, "custom_user_dest", "user's custom exporter should be preserved")
	assert.Contains(t, otelConfig, "custom_user_pipeline", "user's custom pipeline should be preserved")
}
