// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

package scenarios

import (
	"context"
	"testing"

	"github.com/aws-observability/helm-charts/integration-tests/amazon-cloudwatch-observability/util"
	"github.com/aws-observability/helm-charts/integration-tests/amazon-cloudwatch-observability/validations/minikube"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TestOTLPCustomOtelConfig verifies that when a user supplies otelConfig alongside OTEL
// Container Insights, CI is generated by the agent from spec.config (JSON) and the user's
// otelConfig is passed through to spec.otelConfig unchanged. The chart no longer merges CI
// into otelConfig or overrides colliding keys; conflicts are rejected by the agent at runtime.
func TestOTLPCustomOtelConfig(t *testing.T) {
	k8sClient, err := util.NewK8sClient()
	require.NoError(t, err, "failed to create k8s client")

	ns, err := k8sClient.GetNamespace(minikube.Namespace)
	assert.NoError(t, err)
	assert.Equal(t, minikube.Namespace, ns.Name)

	dynamicClient, err := k8sClient.GetDynamicClient()
	require.NoError(t, err, "failed to get dynamic client")

	gvr := getAmazonCloudWatchAgentGVR()

	agent, err := dynamicClient.Resource(gvr).Namespace(minikube.Namespace).Get(
		context.Background(), "cloudwatch-agent", metav1.GetOptions{},
	)
	require.NoError(t, err, "failed to get cloudwatch-agent CR")
	if !assert.NotNil(t, agent, "cloudwatch-agent CR should exist") {
		t.Fatal("cloudwatch-agent CR is nil")
	}

	spec, ok := agent.Object["spec"].(map[string]interface{})
	require.True(t, ok, "spec should be a map")

	// CI is generated by the agent from spec.config (JSON), not baked into otelConfig.
	config, ok := spec["config"].(string)
	require.True(t, ok, "spec.config should be a string")
	minikube.AssertOtelContainerInsights(t, config, "node")

	// The user's otelConfig is passed through to spec.otelConfig verbatim.
	otelConfig, ok := spec["otelConfig"].(string)
	assert.True(t, ok, "otelConfig should be a string")
	assert.NotEmpty(t, otelConfig, "otelConfig should not be empty")

	// User's custom pipeline is preserved.
	assert.Contains(t, otelConfig, "custom_test",
		"user-defined custom pipeline should be preserved in otelConfig")

	// Chart does not override user values on name collision (agent rejects conflicts at runtime).
	assert.Contains(t, otelConfig, "should-be-overwritten",
		"user otelConfig should pass through unchanged (no chart-side override)")

	t.Log("OTLP custom otel config scenario validation passed")
}
