{{/*
OTEL Container Insights LOGS-only otelConfig (hybrid model).

Metrics are generated by the agent from spec.config (JSON); this template supplies
ONLY the CI log pipelines via spec.otelConfig. The agent merges the two at startup.

The shared enrichment processors (resourcedetection, k8sattributes) are named with a
"_logs" suffix so they never collide with the agent's metrics-side copies during that
merge (the agent rejects same-name/different-body components in restricted sections).
Their definitions are otherwise identical.
*/}}
{{- define "otel-container-insights-logs.config" -}}
extensions:
  sigv4auth/cw_k8s_ci_v0_logs_dest:
    region: {{ .Values.region }}
    service: logs
  awscloudwatchlogsprovisioner/cw_k8s_ci_v0_logs:
    region: {{ .Values.region }}
    additional_auth: sigv4auth/cw_k8s_ci_v0_logs_dest

receivers:
  filelog/cw_k8s_ci_v0_app:
    include:
      - /var/log/containers/*.log
    exclude:
      - /var/log/containers/cloudwatch-agent*
      - /var/log/containers/fluent-bit*
      - /var/log/containers/aws-node*
      - /var/log/containers/kube-proxy*
    start_at: end
    include_file_path: true
    include_file_name: false
    max_concurrent_files: 100
    operators:
      - type: regex_parser
        id: extract_metadata_from_filepath
        regex: '^.*\/(?P<pod>[^_]+)_(?P<namespace>[^_]+)_(?P<container>.+)-[a-f0-9]{64}\.log$'
        parse_from: attributes["log.file.path"]
        parse_to: resource
      - type: move
        from: resource.pod
        to: resource["k8s.pod.name"]
      - type: move
        from: resource.namespace
        to: resource["k8s.namespace.name"]
      - type: move
        from: resource.container
        to: resource["k8s.container.name"]
      - id: parse_container_log
        type: container_log_parser

  filelog/cw_k8s_ci_v0_node:
    include:
      - /var/log/messages
      - /var/log/dmesg
      - /var/log/secure
    start_at: end
    include_file_path: true
    include_file_name: false
    max_concurrent_files: 100

processors:
  # Shared enrichment processors — renamed with _logs suffix to avoid collision
  # with the agent's metrics-side copies during the agent-side merge.
  resourcedetection/cw_k8s_ci_v0_logs:
    detectors: [eks, ec2]
    ec2:
      resource_attributes:
        host.id: { enabled: true }
        host.type: { enabled: true }
        host.name: { enabled: true }
        host.image.id: { enabled: true }
        cloud.provider: { enabled: true }
        cloud.platform: { enabled: true }
        cloud.region: { enabled: true }
        cloud.availability_zone: { enabled: true }
        cloud.account.id: { enabled: true }

  k8sattributes/cw_k8s_ci_v0_logs_node:
    auth_type: serviceAccount
    passthrough: false
    filter:
      node_from_env_var: K8S_NODE_NAME
    extract:
      metadata:
        - k8s.node.name
      labels:
        - tag_name: "k8s.node.label.$$$1"
          key_regex: "(.*)"
          from: node
    pod_association:
      - sources:
          - from: resource_attribute
            name: k8s.node.name

  k8sattributes/cw_k8s_ci_v0_logs_pod:
    auth_type: serviceAccount
    passthrough: false
    filter:
      node_from_env_var: K8S_NODE_NAME
    extract:
      metadata:
        - k8s.pod.uid
        - k8s.node.name
        - k8s.deployment.name
        - k8s.statefulset.name
        - k8s.daemonset.name
        - k8s.replicaset.name
        - k8s.job.name
        - k8s.cronjob.name
      labels:
        - tag_name: "k8s.pod.label.$$$1"
          key_regex: "(.*)"
          from: pod
    pod_association:
      - sources:
          - from: resource_attribute
            name: k8s.pod.name
          - from: resource_attribute
            name: k8s.namespace.name

  transform/cw_k8s_ci_v0_logs_set_workload:
    error_mode: ignore
    log_statements:
      - context: resource
        statements:
          - set(attributes["k8s.workload.name"], attributes["k8s.deployment.name"]) where attributes["k8s.deployment.name"] != nil
          - set(attributes["k8s.workload.type"], "Deployment") where attributes["k8s.deployment.name"] != nil
          - set(attributes["k8s.workload.name"], attributes["k8s.statefulset.name"]) where attributes["k8s.workload.name"] == nil and attributes["k8s.statefulset.name"] != nil
          - set(attributes["k8s.workload.type"], "StatefulSet") where attributes["k8s.statefulset.name"] != nil and attributes["k8s.workload.type"] == nil
          - set(attributes["k8s.workload.name"], attributes["k8s.daemonset.name"]) where attributes["k8s.workload.name"] == nil and attributes["k8s.daemonset.name"] != nil
          - set(attributes["k8s.workload.type"], "DaemonSet") where attributes["k8s.daemonset.name"] != nil and attributes["k8s.workload.type"] == nil
          - set(attributes["k8s.workload.name"], attributes["k8s.job.name"]) where attributes["k8s.workload.name"] == nil and attributes["k8s.job.name"] != nil
          - set(attributes["k8s.workload.type"], "Job") where attributes["k8s.job.name"] != nil and attributes["k8s.workload.type"] == nil
          - set(attributes["k8s.workload.name"], attributes["k8s.cronjob.name"]) where attributes["k8s.workload.name"] == nil and attributes["k8s.cronjob.name"] != nil
          - set(attributes["k8s.workload.type"], "CronJob") where attributes["k8s.cronjob.name"] != nil and attributes["k8s.workload.type"] == nil
          - set(attributes["k8s.workload.name"], attributes["k8s.replicaset.name"]) where attributes["k8s.workload.name"] == nil and attributes["k8s.replicaset.name"] != nil
          - set(attributes["k8s.workload.type"], "ReplicaSet") where attributes["k8s.replicaset.name"] != nil and attributes["k8s.workload.type"] == nil
          - set(attributes["service.name"], attributes["k8s.workload.name"]) where attributes["service.name"] == nil and attributes["k8s.workload.name"] != nil

  transform/cw_k8s_ci_v0_logs_set_cluster_and_node:
    error_mode: ignore
    log_statements:
      - context: resource
        statements:
          - set(attributes["k8s.cluster.name"], "{{ .Values.clusterName }}")
          - set(attributes["k8s.node.name"], "${env:K8S_NODE_NAME}")

  transform/cw_k8s_ci_v0_logs_set_cloud_resource_id:
    error_mode: ignore
    log_statements:
      - context: resource
        statements:
          - set(attributes["cloud.resource_id"], Concat(["arn:aws:eks:", attributes["cloud.region"], ":", attributes["cloud.account.id"], ":cluster/", attributes["k8s.cluster.name"]], ""))
            where attributes["cloud.region"] != nil and attributes["cloud.account.id"] != nil and attributes["k8s.cluster.name"] != nil

  transform/cw_k8s_ci_v0_logs_clear_schema_url:
    error_mode: ignore
    log_statements:
      - context: resource
        statements:
          - set(resource.schema_url, "")

  transform/cw_k8s_ci_v0_logs_set_scope_app:
    error_mode: ignore
    log_statements:
      - context: scope
        statements:
          - set(scope.schema_url, "")
          - set(attributes["cloudwatch.source"], "cloudwatch-agent")
          - set(attributes["cloudwatch.solution"], "k8s-otel-container-insights")
          - set(attributes["cloudwatch.pipeline"], "application-logs")

  transform/cw_k8s_ci_v0_logs_set_scope_host:
    error_mode: ignore
    log_statements:
      - context: scope
        statements:
          - set(scope.schema_url, "")
          - set(attributes["cloudwatch.source"], "cloudwatch-agent")
          - set(attributes["cloudwatch.solution"], "k8s-otel-container-insights")
          - set(attributes["cloudwatch.pipeline"], "host-logs")

  batch/cw_k8s_ci_v0_logs_dest:
    send_batch_size: 500
    send_batch_max_size: 500
    timeout: 5s

exporters:
  otlphttp/cw_k8s_ci_v0_app_logs_dest:
    endpoint: {{ if .Values.otelContainerInsights.cloudwatchLogsEndpoint }}{{ .Values.otelContainerInsights.cloudwatchLogsEndpoint | quote }}{{ else if hasKey .Values.adcEndpointOverrides .Values.region }}"https://logs.{{ .Values.region }}.{{ index .Values.adcEndpointOverrides .Values.region }}:443"{{ else }}"https://logs.{{ .Values.region }}.amazonaws.com:443"{{ end }}
    compression: none
    headers:
      x-aws-log-group: "/aws/otel/containerinsights/{{ .Values.clusterName }}/application"
      x-aws-log-stream: "${env:K8S_NODE_NAME}-application"
    sending_queue:
      queue_size: 500
      num_consumers: 10
    tls:
      insecure: false
    auth:
      authenticator: awscloudwatchlogsprovisioner/cw_k8s_ci_v0_logs

  otlphttp/cw_k8s_ci_v0_node_logs_dest:
    endpoint: {{ if .Values.otelContainerInsights.cloudwatchLogsEndpoint }}{{ .Values.otelContainerInsights.cloudwatchLogsEndpoint | quote }}{{ else if hasKey .Values.adcEndpointOverrides .Values.region }}"https://logs.{{ .Values.region }}.{{ index .Values.adcEndpointOverrides .Values.region }}:443"{{ else }}"https://logs.{{ .Values.region }}.amazonaws.com:443"{{ end }}
    compression: none
    headers:
      x-aws-log-group: "/aws/otel/containerinsights/{{ .Values.clusterName }}/host"
      x-aws-log-stream: "${env:K8S_NODE_NAME}-host"
    sending_queue:
      queue_size: 500
      num_consumers: 10
    tls:
      insecure: false
    auth:
      authenticator: awscloudwatchlogsprovisioner/cw_k8s_ci_v0_logs

service:
  extensions:
    - sigv4auth/cw_k8s_ci_v0_logs_dest
    - awscloudwatchlogsprovisioner/cw_k8s_ci_v0_logs
  pipelines:
    logs/cw_k8s_ci_v0_app:
      receivers: [filelog/cw_k8s_ci_v0_app]
      processors:
        - transform/cw_k8s_ci_v0_logs_set_cluster_and_node
        - resourcedetection/cw_k8s_ci_v0_logs
        - transform/cw_k8s_ci_v0_logs_set_cloud_resource_id
        - k8sattributes/cw_k8s_ci_v0_logs_node
        - k8sattributes/cw_k8s_ci_v0_logs_pod
        - transform/cw_k8s_ci_v0_logs_set_scope_app
        - transform/cw_k8s_ci_v0_logs_clear_schema_url
        - transform/cw_k8s_ci_v0_logs_set_workload
        - batch/cw_k8s_ci_v0_logs_dest
      exporters:
        - otlphttp/cw_k8s_ci_v0_app_logs_dest

    logs/cw_k8s_ci_v0_node:
      receivers: [filelog/cw_k8s_ci_v0_node]
      processors:
        - transform/cw_k8s_ci_v0_logs_set_cluster_and_node
        - resourcedetection/cw_k8s_ci_v0_logs
        - transform/cw_k8s_ci_v0_logs_set_cloud_resource_id
        - k8sattributes/cw_k8s_ci_v0_logs_node
        - transform/cw_k8s_ci_v0_logs_set_scope_host
        - transform/cw_k8s_ci_v0_logs_clear_schema_url
        - batch/cw_k8s_ci_v0_logs_dest
      exporters:
        - otlphttp/cw_k8s_ci_v0_node_logs_dest
{{- end -}}
