{{- if and (.Values.admissionWebhooks.create) (.Values.admissionWebhooks.certManager.enabled) (or .Values.admissionWebhooks.agents.create .Values.admissionWebhooks.instrumentations.create .Values.admissionWebhooks.pods.create .Values.admissionWebhooks.workloads.create .Values.admissionWebhooks.namespaces.create) }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ printf "%s/%s-serving-cert" .Release.Namespace (include "amazon-cloudwatch-observability.name" .) }}
  labels:
    {{- include "amazon-cloudwatch-observability.labels" . | nindent 4}}
  name: {{ template "amazon-cloudwatch-observability.name" . }}-mutating-webhook-configuration
webhooks:
{{- if .Values.admissionWebhooks.instrumentations.create }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ template "amazon-cloudwatch-observability.webhookServiceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-cloudwatch-aws-amazon-com-v1alpha1-instrumentation
  failurePolicy: {{ .Values.admissionWebhooks.instrumentations.failurePolicy | default .Values.admissionWebhooks.failurePolicy }}
  name: minstrumentation.kb.io
  {{- if .Values.admissionWebhooks.instrumentations.namespaceSelector }}
  namespaceSelector:
  {{- toYaml .Values.admissionWebhooks.instrumentations.namespaceSelector | nindent 6 }}
  {{- else if .Values.admissionWebhooks.namespaceSelector }}
  namespaceSelector:
  {{- toYaml .Values.admissionWebhooks.namespaceSelector | nindent 6 }}
  {{- end }}
  {{- if .Values.admissionWebhooks.objectSelector }}
  objectSelector:
  {{- toYaml .Values.admissionWebhooks.objectSelector | nindent 6 }}
  {{- end }}
  rules:
  - apiGroups:
    - cloudwatch.aws.amazon.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - instrumentations
  sideEffects: None
  timeoutSeconds: {{ .Values.admissionWebhooks.timeoutSeconds }}
{{- end }}
{{- if .Values.admissionWebhooks.agents.create }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ template "amazon-cloudwatch-observability.webhookServiceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-cloudwatch-aws-amazon-com-v1alpha1-amazoncloudwatchagent
  failurePolicy: {{ .Values.admissionWebhooks.agents.failurePolicy | default .Values.admissionWebhooks.failurePolicy }}
  name: mamazoncloudwatchagent.kb.io
  {{- if .Values.admissionWebhooks.agents.namespaceSelector }}
  namespaceSelector:
  {{- toYaml .Values.admissionWebhooks.agents.namespaceSelector | nindent 6 }}
  {{- else if .Values.admissionWebhooks.namespaceSelector }}
  namespaceSelector:
  {{- toYaml .Values.admissionWebhooks.namespaceSelector | nindent 6 }}
  {{- end }}
  {{- if .Values.admissionWebhooks.objectSelector }}
  objectSelector:
  {{- toYaml .Values.admissionWebhooks.objectSelector | nindent 6 }}
  {{- end }}
  rules:
  - apiGroups:
    - cloudwatch.aws.amazon.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - amazoncloudwatchagents
  sideEffects: None
  timeoutSeconds: {{ .Values.admissionWebhooks.timeoutSeconds }}
{{- end }}
{{- if .Values.admissionWebhooks.pods.create }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ template "amazon-cloudwatch-observability.webhookServiceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1-pod
  failurePolicy: {{ .Values.admissionWebhooks.pods.failurePolicy | default .Values.admissionWebhooks.failurePolicy }}
  name: mpod.kb.io
  {{- if .Values.admissionWebhooks.pods.namespaceSelector }}
  namespaceSelector:
  {{- toYaml .Values.admissionWebhooks.pods.namespaceSelector | nindent 6 }}
  {{- else if .Values.admissionWebhooks.namespaceSelector }}
  namespaceSelector:
  {{- toYaml .Values.admissionWebhooks.namespaceSelector | nindent 6 }}
  {{- end }}
  {{- if .Values.admissionWebhooks.objectSelector }}
  objectSelector:
  {{- toYaml .Values.admissionWebhooks.objectSelector | nindent 6 }}
  {{- end }}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None
  timeoutSeconds: {{ .Values.admissionWebhooks.timeoutSeconds }}
{{- end }}
{{- if .Values.admissionWebhooks.namespaces.create }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ template "amazon-cloudwatch-observability.webhookServiceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1-namespace
  failurePolicy: {{ .Values.admissionWebhooks.namespaces.failurePolicy | default .Values.admissionWebhooks.pods.failurePolicy | default .Values.admissionWebhooks.failurePolicy }}
  name: mnamespace.kb.io
  {{- if .Values.admissionWebhooks.namespaces.namespaceSelector }}
  namespaceSelector:
  {{- toYaml .Values.admissionWebhooks.namespaces.namespaceSelector | nindent 6 }}
  {{- else if .Values.admissionWebhooks.namespaceSelector }}
  namespaceSelector:
  {{- toYaml .Values.admissionWebhooks.namespaceSelector | nindent 6 }}
  {{- end }}
  {{- if .Values.admissionWebhooks.objectSelector }}
  objectSelector:
  {{- toYaml .Values.admissionWebhooks.objectSelector | nindent 6 }}
  {{- end }}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - namespaces
  sideEffects: None
  timeoutSeconds: {{ .Values.admissionWebhooks.timeoutSeconds }}
{{- end }}
{{- if .Values.admissionWebhooks.workloads.create }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ template "amazon-cloudwatch-observability.webhookServiceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1-workload
  failurePolicy: {{ .Values.admissionWebhooks.workloads.failurePolicy | default .Values.admissionWebhooks.pods.failurePolicy | default .Values.admissionWebhooks.failurePolicy }}
  name: mworkload.kb.io
  {{- if .Values.admissionWebhooks.workloads.namespaceSelector }}
  namespaceSelector:
  {{- toYaml .Values.admissionWebhooks.workloads.namespaceSelector | nindent 6 }}
  {{- else if .Values.admissionWebhooks.namespaceSelector }}
  namespaceSelector:
  {{- toYaml .Values.admissionWebhooks.namespaceSelector | nindent 6 }}
  {{- end }}
  {{- if .Values.admissionWebhooks.objectSelector }}
  objectSelector:
  {{- toYaml .Values.admissionWebhooks.objectSelector | nindent 6 }}
  {{- end }}
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - daemonsets
    - deployments
    - statefulsets
  sideEffects: None
  timeoutSeconds: {{ .Values.admissionWebhooks.timeoutSeconds }}
{{- end }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ printf "%s/%s-serving-cert" .Release.Namespace (include "amazon-cloudwatch-observability.name" .) }}
  labels:
    {{- include "amazon-cloudwatch-observability.labels" . | nindent 4}}
  name: {{ template "amazon-cloudwatch-observability.name" . }}-validating-webhook-configuration
webhooks:
{{- if .Values.admissionWebhooks.instrumentations.create }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ template "amazon-cloudwatch-observability.webhookServiceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /validate-cloudwatch-aws-amazon-com-v1alpha1-instrumentation
  failurePolicy: {{ .Values.admissionWebhooks.instrumentations.failurePolicy | default .Values.admissionWebhooks.failurePolicy }}
  name: vinstrumentationcreateupdate.kb.io
  {{- if .Values.admissionWebhooks.instrumentations.namespaceSelector }}
  namespaceSelector:
  {{- toYaml .Values.admissionWebhooks.instrumentations.namespaceSelector | nindent 6 }}
  {{- else if .Values.admissionWebhooks.namespaceSelector }}
  namespaceSelector:
  {{- toYaml .Values.admissionWebhooks.namespaceSelector | nindent 6 }}
  {{- end }}
  {{- if .Values.admissionWebhooks.objectSelector }}
  objectSelector:
  {{- toYaml .Values.admissionWebhooks.objectSelector | nindent 6 }}
  {{- end }}
  rules:
  - apiGroups:
    - cloudwatch.aws.amazon.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - instrumentations
  sideEffects: None
  timeoutSeconds: {{ .Values.admissionWebhooks.timeoutSeconds }}
{{- end }}
{{- if .Values.admissionWebhooks.instrumentations.create }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ template "amazon-cloudwatch-observability.webhookServiceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /validate-cloudwatch-aws-amazon-com-v1alpha1-instrumentation
  failurePolicy: Ignore
  name: vinstrumentationdelete.kb.io
  {{- if .Values.admissionWebhooks.instrumentations.namespaceSelector }}
  namespaceSelector:
  {{- toYaml .Values.admissionWebhooks.instrumentations.namespaceSelector | nindent 6 }}
  {{- else if .Values.admissionWebhooks.namespaceSelector }}
  namespaceSelector:
  {{- toYaml .Values.admissionWebhooks.namespaceSelector | nindent 6 }}
  {{- end }}
  {{- if .Values.admissionWebhooks.objectSelector }}
  objectSelector:
  {{- toYaml .Values.admissionWebhooks.objectSelector | nindent 6 }}
  {{- end }}
  rules:
  - apiGroups:
    - cloudwatch.aws.amazon.com
    apiVersions:
    - v1alpha1
    operations:
    - DELETE
    resources:
    - instrumentations
  sideEffects: None
  timeoutSeconds: {{ .Values.admissionWebhooks.timeoutSeconds }}
{{- end }}
{{- if .Values.admissionWebhooks.agents.create }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ template "amazon-cloudwatch-observability.webhookServiceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /validate-cloudwatch-aws-amazon-com-v1alpha1-amazoncloudwatchagent
  failurePolicy: {{ .Values.admissionWebhooks.agents.failurePolicy | default .Values.admissionWebhooks.failurePolicy }}
  name: vamazoncloudwatchagentcreateupdate.kb.io
  {{- if .Values.admissionWebhooks.agents.namespaceSelector }}
  namespaceSelector:
  {{- toYaml .Values.admissionWebhooks.agents.namespaceSelector | nindent 6 }}
  {{- else if .Values.admissionWebhooks.namespaceSelector }}
  namespaceSelector:
  {{- toYaml .Values.admissionWebhooks.namespaceSelector | nindent 6 }}
  {{- end }}
  {{- if .Values.admissionWebhooks.objectSelector }}
  objectSelector:
  {{- toYaml .Values.admissionWebhooks.objectSelector | nindent 6 }}
  {{- end }}
  rules:
  - apiGroups:
    - cloudwatch.aws.amazon.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - amazoncloudwatchagents
  sideEffects: None
  timeoutSeconds: {{ .Values.admissionWebhooks.timeoutSeconds }}
{{- end }}
{{- if .Values.admissionWebhooks.agents.create }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ template "amazon-cloudwatch-observability.webhookServiceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /validate-cloudwatch-aws-amazon-com-v1alpha1-amazoncloudwatchagent
  failurePolicy: Ignore
  name: vamazoncloudwatchagentdelete.kb.io
  {{- if .Values.admissionWebhooks.agents.namespaceSelector }}
  namespaceSelector:
  {{- toYaml .Values.admissionWebhooks.agents.namespaceSelector | nindent 6 }}
  {{- else if .Values.admissionWebhooks.namespaceSelector }}
  namespaceSelector:
  {{- toYaml .Values.admissionWebhooks.namespaceSelector | nindent 6 }}
  {{- end }}
  {{- if .Values.admissionWebhooks.objectSelector }}
  objectSelector:
  {{- toYaml .Values.admissionWebhooks.objectSelector | nindent 6 }}
  {{- end }}
  rules:
  - apiGroups:
    - cloudwatch.aws.amazon.com
    apiVersions:
    - v1alpha1
    operations:
    - DELETE
    resources:
    - amazoncloudwatchagents
  sideEffects: None
  timeoutSeconds: {{ .Values.admissionWebhooks.timeoutSeconds }}
{{- end }}
{{- end }}
