{{- if .Values.agent.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cloudwatch-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    k8sMode: {{ $.Values.k8sMode}}
{{- end }}
