{{ if .Values.agent.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "amazon-cloudwatch-observability.labels" . | nindent 4}}
  name: {{ template "cloudwatch-agent.name" . }}-role
rules:
- apiGroups: [ "" ]
  resources: [ "pods", "pods/logs", "nodes", "nodes/proxy", "namespaces", "endpoints" ]
  verbs: [ "list", "watch", "get" ]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["list", "watch", "get"]
- apiGroups: [ "" ]
  resources: [ "services" ]
  verbs: [ "list", "watch" ]
- apiGroups: [ "apps" ]
  resources: [ "replicasets", "daemonsets", "deployments", "statefulsets" ]
  verbs: [ "list", "watch", "get" ]
- apiGroups: [ "batch" ]
  resources: [ "jobs" ]
  verbs: [ "list", "watch" ]
- apiGroups: [ "networking.k8s.io" ]
  resources: [ "ingresses" ]
  verbs: [ "list", "watch", "get" ]
- apiGroups: [ "" ]
  resources: [ "nodes/stats", "configmaps", "events" ]
  verbs: [ "create", "get" ]
- apiGroups: [ "" ]
  resources: [ "configmaps" ]
  verbs: [ "update" ]
- apiGroups: [ "" ]
  resources: [ "persistentvolumeclaims", "persistentvolumes" ]
  verbs: [ "get", "list", "watch" ]
- nonResourceURLs: [ "/metrics" ]
  verbs: [ "get", "list", "watch" ]
{{- end }}
