{{- if .Values.agent.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cloudwatch-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "cloudwatch-agent.serviceAccountAnnotations" . | nindent 4}}
{{- end }}
