{{- if eq .Values.k8sMode "GKE" }}
{{- /*
On GKE, a pod that uses the system-node-critical or system-cluster-critical PriorityClass is only admitted in a
namespace that has a ResourceQuota with a scopeSelector that matches that class. The agent and fluent-bit run
at system-node-critical by default.
Ref: https://kubernetes.io/docs/concepts/policy/resource-quotas/#limit-priority-class-consumption-by-default
*/ -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    {{- include "amazon-cloudwatch-observability.labels" . | nindent 4}}
  name: gcp-critical-pods
  namespace: {{ .Release.Namespace }}
spec:
  scopeSelector:
    matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values:
          - system-node-critical
          - system-cluster-critical
{{- end }}
