name: Run Image Scan for Amazon CloudWatch Observability Helm Chart

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches:
      - main
  workflow_dispatch:

jobs:
  ContainerScan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Get values.yaml for parsing"
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: values_yaml
        with:
          config: charts/amazon-cloudwatch-observability/values.yaml

      - name: "[DCGM Exporter] Scan for vulnerabilities"
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ${{ steps.read_yaml.outputs['dcgmExporter.public'] }}/${{ steps.read_yaml.outputs['dcgmExporter.repository'] }}:${{ steps.read_yaml.outputs['dcgmExporter.tag'] }}
          severity_threshold: HIGH