name: Run Image Scan for Amazon CloudWatch Observability Helm Chart

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches:
      - main
  workflow_dispatch:

jobs:
  ContainerScan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Get values.yaml for parsing"
        uses: mikefarah/yq@master
        with:
          cmd:
            export DCGM_EXPORTER_IMAGE=$(yq '.dcgmExporter.image.repositoryDomainMap.public' charts/amazon-cloudwatch-observability/values.yaml)/$(yq '.dcgmExporter.image.repository' charts/amazon-cloudwatch-observability/values.yaml):$(yq '.dcgmExporter.image.tag' charts/amazon-cloudwatch-observability/values.yaml)

      - name: "[DCGM Exporter] Scan for vulnerabilities"
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: $DCGM_EXPORTER_IMAGE
          severity_threshold: HIGH